[project]
name = "discord-music-bot"
version = "1.0.0"
description = "Bot de mÃºsica para Discord con soporte 24/7"
authors = []
dependencies = [
    "discord.py>=2.3.2",
    "yt-dlp>=2023.12.30",
    "PyNaCl>=1.5.0",
    "flask>=3.0.0"
]

[tool.pyright]
venvPath = "."
venv = ".venv"
